### ISSUE TITLE
Question about manifest items dependencies

### ISSUE THREAD

**Issue by ubermuda** [dantleech/maestro#14]
Hi Dan, first thank you for working on this, it is a much needed tool and it already looks very interesting :)

I have tried to implement a new job type (to get a grip of how it works mostly), and I seem to have a bug I don't quite understand. The job type is `assert-file-exists` and checks whether a file exists or not.

The problem I have is when I apply my manifest with a configuration that I know will fail, the apply succeeds (although the job itself does fail)

I have created a PR on my fork with more details : https://github.com/ubermuda/maestro/pull/1

So, I guess I have missed something in the dependency  or queue system but I don't know what? Any pointer would be appreciated :)

Thanks again,

**Comment by dantleech** [comment]
Hey, thanks for taking a look.

The whole project is still embryonic, and I'm still trying to understand how it should work, so any feedback is very welcome :)

it seems that failing jobs do not currently terminate the queue, I created a pull request on your fork: https://github.com/ubermuda/maestro/pull/2

**Comment by ubermuda** [comment]
It does indeed solve the issue ! Thank you

So now that I have a better understanding of the philosophy of the project, I am looking for the best way to help :) Is there a specific subject that you would like to help with? I can also give you my feedback as an external contributor on the state of the project if you'd like? (I have both good and bad things to say ;)

**Comment by dantleech** [comment]
> Is there a specific subject that you would like to help with?

I am concerned currently with the target/job/queue/monitoring system - generally the core domain. I'm not happy with the current state of the queue dispatcher, and suspect there are a few other key things I've missed. So any advice here would be good.

>  I can also give you my feedback as an external contributor on the state of the project if you'd like?

Absolutely -- the more feedback the better :)

**Comment by dantleech** [comment]
I started sketching a new version: https://github.com/dantleech/maestro/pull/17

**Comment by dantleech** [comment]
The new version has been merged into master, I think it's better, it can run as a server and uses a graph to manage the tasks. Still some way to go.

**Comment by ubermuda** [comment]
nice! sorry I don't have much time right now (family visiting :) but I'll try to have a look asap!

**Comment by dantleech** [comment]
No worries :) would also be happy to do a hangout to discuss if you'd like.

On 27 May 2019 01:03:48 CEST, Geoffrey Bachelet <notifications@github.com> wrote:
>nice! sorry I don't have much time right now (family visiting :) but
>I'll try to have a look asap!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/dantleech/maestro/issues/14#issuecomment-496038369

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dantleech** [comment]
It's been completely refactored now :)
